# This file has been generated by node2nix 1.11.1. Do not edit!
{
  nodeEnv,
  fetchurl,
  fetchgit,
  nix-gitignore,
  stdenv,
  lib,
  globalBuildInputs ? [],
}: let
  sources = {};
  args = {
    name = "typhon-webapp";
    packageName = "typhon-webapp";
    version = "0.0.1";
    src = ../../typhon-webapp/assets;
    buildInputs = globalBuildInputs;
    meta = {
      license = "AGPL-3.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = false;
  };
in {
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src =
        nix-gitignore.gitignoreSourcePure [
          "*"
          "!package.json"
          "!package-lock.json"
        ]
        args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
