# This file has been generated by node2nix 1.11.1. Do not edit!

{
  nodeEnv,
  fetchurl,
  fetchgit,
  nix-gitignore,
  stdenv,
  lib,
  globalBuildInputs ? [ ],
}:

let
  sources = {
    "@fontsource/jetbrains-mono-5.1.0" = {
      name = "_at_fontsource_slash_jetbrains-mono";
      packageName = "@fontsource/jetbrains-mono";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@fontsource/jetbrains-mono/-/jetbrains-mono-5.1.0.tgz";
        sha512 = "YzWpGYY3PoqvmvwW2Hb4NwkN5C7LO0FmZugEGcFe6cNNE/cMgH9JhW5LI6hjG+1+nwgSHyJtKmblHNrUqlyhWg==";
      };
    };
    "@fontsource/roboto-5.1.0" = {
      name = "_at_fontsource_slash_roboto";
      packageName = "@fontsource/roboto";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@fontsource/roboto/-/roboto-5.1.0.tgz";
        sha512 = "cFRRC1s6RqPygeZ8Uw/acwVHqih8Czjt6Q0MwoUoDe9U3m4dH1HmNDRBZyqlMSFwgNAUKgFImncKdmDHyKpwdg==";
      };
    };
  };
  args = {
    name = "typhon-webapp";
    packageName = "typhon-webapp";
    version = "0.0.1";
    src = ../../typhon-webapp/assets;
    dependencies = [
      sources."@fontsource/jetbrains-mono-5.1.0"
      sources."@fontsource/roboto-5.1.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      license = "AGPL-3.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (
    lib.overrideExisting args {
      src = stdenv.mkDerivation {
        name = args.name + "-package-json";
        src = nix-gitignore.gitignoreSourcePure [
          "*"
          "!package.json"
          "!package-lock.json"
        ] args.src;
        dontBuild = true;
        installPhase = "mkdir -p $out; cp -r ./* $out;";
      };
    }
  );
}
