# This file has been generated by node2nix 1.11.1. Do not edit!
{
  nodeEnv,
  fetchurl,
  fetchgit,
  nix-gitignore,
  stdenv,
  lib,
  globalBuildInputs ? [],
}: let
  sources = {
    "@fontsource/jetbrains-mono-4.5.12" = {
      name = "_at_fontsource_slash_jetbrains-mono";
      packageName = "@fontsource/jetbrains-mono";
      version = "4.5.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/@fontsource/jetbrains-mono/-/jetbrains-mono-4.5.12.tgz";
        sha512 = "LJF1ala1/u+wXZmESFqIk08FA9yGX4/uAAleCHmXUMgEjvNAYFHUQQ7eK5hQQoBOwh99cU5suTrqYqEkgzwzPA==";
      };
    };
    "@fontsource/roboto-4.5.8" = {
      name = "_at_fontsource_slash_roboto";
      packageName = "@fontsource/roboto";
      version = "4.5.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@fontsource/roboto/-/roboto-4.5.8.tgz";
        sha512 = "CnD7zLItIzt86q4Sj3kZUiLcBk1dSk81qcqgMGaZe7SQ1P8hFNxhMl5AZthK1zrDM5m74VVhaOpuMGIL4gagaA==";
      };
    };
  };
  args = {
    name = "typhon-webapp";
    packageName = "typhon-webapp";
    version = "0.0.1";
    src = ../../typhon-webapp/assets;
    dependencies = [
      sources."@fontsource/jetbrains-mono-4.5.12"
      sources."@fontsource/roboto-4.5.8"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      license = "AGPL-3.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in {
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src =
        nix-gitignore.gitignoreSourcePure [
          "*"
          "!package.json"
          "!package-lock.json"
        ]
        args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
